#!/bin/bash

# ------------------------------------------------------------------------------
# Functions
# ------------------------------------------------------------------------------

get_os() {

    local os=""
    local kernelName=""

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    kernelName="$(uname -s)"

    if [ "$kernelName" == "Darwin" ]; then
        os="macos"
    elif [ "$kernelName" == "Linux" ] && [ -e "/etc/lsb-release" ]; then
        os="ubuntu"
    else
        os="$kernelName"
    fi

    printf "%s" "$os"

}

source_bash_files() {

    declare -r CURRENT_DIRECTORY="$(pwd)"

    declare -r -a FILES_TO_SOURCE=(
        "aliases/bash_aliases"
        "autocomplete/bash_autocomplete"
#        "autocomplete/git_autocomplete"
        "bash_exports"
        "bash_includes"
        "bash_functions"
        "bash_options"
        "bash_prompt"
        # Clear console on exit to increase privacy
        "bash_logout"
        "bash.local"  # For local settings that should not be under version control.

    )

    local file=""
    local i=""

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    cd "$(dirname "$(readlink "${BASH_SOURCE[0]}")")"

    # shellcheck disable=SC2034
    declare -r OS="$(get_os)"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    for i in ${!FILES_TO_SOURCE[*]}; do

        file="$HOME/.bash/${FILES_TO_SOURCE[$i]}"

        [ -r "$file" ] \
            && . "$file"

    done

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    cd "$CURRENT_DIRECTORY"

}

# ------------------------------------------------------------------------------
# Main
# ------------------------------------------------------------------------------

source_bash_files

# Remove Unused Function Alias. Important after renaming or removing a function in your .bashrc file.
# unset -f my_function
unset -f source_bash_files

# ------------------------------------------------------------------------------

# Brewfile manager for Homebrew at OS X.

if [ -f $(brew --prefix)/etc/brew-wrap ];then
  source $(brew --prefix)/etc/brew-wrap
fi

# Homebrew Command Not Found
# https://github.com/Homebrew/homebrew-command-not-found
if brew command command-not-found-init > /dev/null 2>&1; then eval "$(brew command-not-found-init)"; fi

# Clear system messages (system copyright notice, the date
# and time of the last login, the message of the day, etc.).
#clear
