#!/usr/bin/env bash

# How do I find all files containing specific text on Linux?
grep -rnw '/path/to/somewhere/' -e 'Pattern'
# -r or -R is recursive,
# -n is line number, and
# -w stands for match the whole word.
# -l (lower-case L) can be added to just give the file name of matching files.
# Along with these, --exclude, --include, --exclude-dir flags could be used for efficient searching:
# This will only search through those files which have .c or .h extensions:
grep --include=\*.{c,h} -rnw '/path/to/somewhere/' -e "Pattern"
# This will exclude searching all the files ending with .o extension:
grep --exclude=*.o -rnw '/path/to/somewhere/' -e "Pattern"
# For directories it's possible to exclude a particular directory(ies) through --exclude-dir parameter.
# For example, this will exclude the dirs dir1/, dir2/ and all of them matching *.dst/:
grep --exclude-dir={dir1,dir2,*.dst} -rnw '/path/to/somewhere/' -e "Pattern"

grep -rnw --include=*.java . -e "Whatever I'm looking for"
# Or a command similar to the one you are trying (example: ) for searching in all javascript files (*.js):
find . -name '*.js' -exec grep -i 'string to search for' {} \; -print
# This will print the lines in the files where the text appears, but it does not print the file name.


# Exclude comments after # from file
grep '^[^#]' /path/to/conf.file
grep -v -E "#|^$" /path/to/conf.file

#  Check host SSL certificate
openssl s_client -connect smtp.gmail.com:587 -starttls smtp

# How to check which shell am I using?
echo $SHELL
ps -p "$$"

grep --include=*.xlsx -rnw '/Volumes/Data'

ls -R /Volumes/Data | grep "*Box*\.efi$"

find /Volumes/Data -type f -iname "*tel*.xlsx"
locate "/Volumes/Data/*/*.xlsx"
