#!/bin/bash

# https://bitbucket.org/artemb/wrap/src/tip/src/wrap?fileviewer=file-view-default
# https://habrahabr.ru/post/67746/

FAIL_SOUND=/usr/share/sounds/wrap_failure.wav
SUCCESS_SOUND=/usr/share/sounds/wrap_success.wav

if [ $# -gt 0 ]; then
  "$@"
  EXIT_CODE=$?
  if [ $EXIT_CODE -eq 0 ]; then
    notify-send -i gtk-apply Success "$*" && aplay -q $SUCCESS_SOUND &
  else
    notify-send -i gtk-dialog-error Failure "$*" && aplay -q $FAIL_SOUND &
  fi
else
  notify-send -i gtk-apply "Finished" && aplay -q $SUCCESS_SOUND &
fi

exit $EXIT_CODE
