#!/usr/bin/env zsh

# Path to your oh-my-zsh installation.
#ZSH=$HOME/.zsh/plugins/oh-my-zsh
#export FPATH=$HOME/usr/share/zsh/'version of zsh'/functions:$FPATH

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH

# Better DIR color
export LS_COLORS="di=1;;94:*.tar=00;31:*.gz=00;31:*.zip=00;31"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
autoload -Uz compinit
compinit

# History options
export HISTFILE=~/.zsh/zsh_history
export HISTSIZE=200000
export SAVEHIST=100000

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
#HIST_STAMPS="yyyy-mm-dd"
