#!/bin/bash

# Load OS specific files.

[ -f "$HOME/.bash/autocomplete/$OS/bash_autocomplete" ] \
    && . "$HOME/.bash/autocomplete/$OS/bash_autocomplete"


# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;
