#!/bin/bash

# For a full list of active aliases, run `alias`.

##### MAC ONLY #####################################################
if [ `uname` == "Darwin" ]; then
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # MacOS does not have sudoedit by default! Fix this with an alias
  alias sudoedit="sudo -e"


  # Short-cuts for copy-paste.
  alias c='pbcopy'
  alias p='pbpaste'

  # Remove all items safely, to Trash (`brew install trash`).
  #alias rm='trash'

  # Lock screen.

  alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # tmux helpers

  alias tmuxkw="tmux kill-window -t"
  alias tmuxkp="tmux kill-pane -t"
  alias tmuxks="tmux kill-session -t"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # Shorter commands for `Homebrew`.

  alias brewd="brew doctor"
  alias brewi="brew install"
  alias brewr="brew uninstall"
  alias brews="brew search"
  alias brewu="brew update \
                && brew upgrade --force-bottle --cleanup\
                && brew cleanup \
                && brew cask cleanup \
                && brew prune \
                && brew doctor \
                && npm-check -g -u"
  alias cask="brew cask"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  alias npmu="npm install npm -g \
              && npm update -g"

  alias gemu="sudo gem update --system \
                && sudo gem update --no-rdoc --no-ri"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # Update applications and CLTs.
  alias u="sudo softwareupdate --install --all \
            && brewu \
            && gemu \
            && npmu"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # Flush DNS cache.
  alias flushdns="sudo dscacheutil -flushcache; \
                       sudo killall -HUP mDNSResponder"


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # Empty the trash, the main HDD and on all mounted volumes,
  # and clear Apple’s system logs to improve shell startup speed.
  alias empty-trash="sudo rm -frv /Volumes/*/.Trashes; \
                   sudo rm -frv ~/.Trash; \
                   sudo rm -frv /private/var/log/asl/*.asl; \
                   sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # Hide/Show desktop icons.
  alias hide-desktop-icons="defaults write com.apple.finder CreateDesktop -bool false \
                            && killall Finder"

  alias show-desktop-icons="defaults write com.apple.finder CreateDesktop -bool true \
                            && killall Finder"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # Networking
  alias localip="ipconfig getifaddr en1"
  # alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
  alias extip="dig +short myip.opendns.com @resolver1.opendns.com"
  alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"
  #alias dig="dig +nocmd any +multiline +noall +answer"

  # View HTTP traffic
  alias sniff="sudo ngrep -W byline -d 'en0' -t '^(GET|POST) ' 'tcp and port 80'"
  alias httpdump="sudo tcpdump -i en0 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # Open from the terminal.
  alias o="open"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # macOS has no `md5sum`, so use `md5` as a fallback
  command -v md5sum > /dev/null || alias md5sum="md5"

  # macOS has no `sha1sum`, so use `shasum` as a fallback
  command -v sha1sum > /dev/null || alias sha1sum="shasum"

  # Recursively delete `.DS_Store` files
  alias cleanupDS="find . -type f -name '*.DS_Store' -ls -delete"

  # Empty the Trash on all mounted volumes and the main HDD.
  # Also, clear Apple’s System Logs to improve shell startup speed.
  # Finally, clear download history from quarantine. https://mths.be/bum
  alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

  # Show/hide hidden files in Finder
  alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
  alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

  # Hide/show all desktop icons (useful when presenting)
  alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
  alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

  # Merge PDF files
  # Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`
  alias mergepdf='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'

  # Disable Spotlight
  alias spotoff="sudo mdutil -a -i off"
  # Enable Spotlight
  alias spoton="sudo mdutil -a -i on"

  # Ring the terminal bell, and put a badge on Terminal.app’s Dock icon
  # (useful when executing time-consuming commands)
  alias badge="tput bel"

  # Stuff I never really use but cannot delete either because of http://xkcd.com/530/
  alias mutevolume="osascript -e 'set volume output muted true'"
  alias upvolume="osascript -e 'set volume output volume 100'"

  alias eject_all="osascript -e 'tell application \"Finder\" to eject (every disk whose ejectable is true)'"

  # Kill all the tabs in Chrome to free up memory
  # [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
  alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

  alias chrome="/Applications/Google\\ \\Chrome.app/Contents/MacOS/Google\\ \\Chrome"
  #alias canary="/Applications/Google\\ Chrome\\ Canary.app/Contents/MacOS/Google\\ Chrome\\ Canary"

  # Print each PATH entry on a separate line
  alias path='echo -e ${PATH//:/\\n}'

  alias yt="cd ~/Downloads && youtube-dl"

  # replace nano with brewed nano
  [[ -f "/usr/local/bin/nano" ]] && alias nano="/usr/local/bin/nano"

  alias todo="todo.sh"

  # export defaults to file /tmp/defaults
  alias deftmp="defaults read > /tmp/defaults"

fi
##### MAC ONLY #####################################################
