#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Git aliases
# More Git tips http://firstaidgit.io/
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias g="git"
alias gam='git commit -am'
alias gap='git add -p' # step through each change, or hunk
alias gb='git branch'
alias gbt=git_list_branches
alias gc='git checkout'
alias gchp='git cherry-pick' # cherry pick the committed code in your own branch (gchp [hash])
alias gcl='git clone'
alias gcln='git clean -xfd' # remove untracked files
alias gd='git diff'
alias gdtp='git stash pop' # bring back your changes, but it removes them from your stash
alias gf='git reflog' # allows you to see every step you have made with git allowing you to retract and reinstate your steps
alias ggmp='git checkout -' # jump back to to your last branch
alias gh="github"
alias gl='git log'
alias glt='git log --all --graph --decorate --oneline --simplify-by-decoration' # pretty branch status
alias glp5='git log -5 --pretty --oneline' # view your last 5 latest commits each on their own line
alias glsw='git log -S' # search the commit history for the word puppy and display matching commits (glsw [word])
alias gm='git commit -m'
alias gp="git push origin HEAD"
alias gpu='git pull origin HEAD --prune'
alias gpt="git push origin HEAD && git push --tags"
# `cd` to Git repo root
alias gr='[ ! -z `git rev-parse --show-cdup` ] && cd `git rev-parse --show-cdup || pwd`'
alias gra='git remote add'
alias grok="ngrok start rem.jsbin-dev.com static.rem.jsbin-dev.com learn.rem.jsbin-dev.com"
alias grr='git remote rm'
alias gs='git status'
alias gsl='git shortlog -sn' # quickly get a list of contributors and see how many commits each person has
alias gss="git status -s"
alias gst='git stash' # stash git changes and put them into your list
alias gta='git tag -a -m'
alias gws='git diff --shortstat "@{0 day ago}"' # how many lines of code you have written today
alias gwts='git ls-files | xargs wc -l' # count number of lines of code in a git project
alias wip="git commit -m'WIP' . && git push origin HEAD"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Undo a `git push`
alias undopush="git push -f origin HEAD^:master"

# Gist
alias gist-paste="gist --private --copy --paste --filename"  # gist-paste filename.ext -- create private Gist from the clipboard contents
alias gist-file="gist --private --copy"  # gist-file filename.ext -- create private Gist from a file
