#!/bin/bash

if [ $# -eq 1  ]; then
  osascript -e "display notification \"$1\" with title \"Notification\""
elif [ $# -eq 2  ]; then
  osascript -e "display notification \"$2\" with title \"$1\""
elif [ $# -eq 3  ]; then
  osascript -e "display notification \"$3\" with title \"$1\"  subtitle \"$2\""
else
  echo "Can only be run with 1/2/3 arguments"
fi

# Safer solution from https://apple.stackexchange.com/questions/57412/how-can-i-trigger-a-notification-center-notification-from-an-applescript-or-shel/115373#115373
# X="$*" /usr/bin/osascript -e 'display notification system attribute "X"'
