#!/bin/bash

clear

echo "Loading profile..."
# bash will try to source .bash_profile first, but if that doesn't exist, it will source .profile
# if running bash
if [ "${BASH-no}" != "no" ]; then
		# include .bashrc if it exists
		if [ -f "$HOME/.bashrc" ]; then
				[ -r $HOME/.bashrc ] && . $HOME/.bashrc
		fi
fi

# ------------------------------------------------------------------------------
# MACOS X / DARWIN SPECIFIC
# ------------------------------------------------------------------------------

#if [ "$(uname)" == "Darwin" ]; then
#
#fi

# ------------------------------------------------------------------------------
# END MACOS X / DARWIN SPECIFIC
# ------------------------------------------------------------------------------

cat << EOF
#-------------------------------------------------------#
#                ___   ___  __  ___                     #
#         __ _  / _ | / _ \/  |/  / ___  _______        #
#        /  ' \/ __ |/ // / /|_/ / / _ \/ __/ _ \       #
#       /_/_/_/_/ |_/____/_/  /_(_) .__/_/  \___/       #
#                                /_/                    #
#                                                       #
#-------------------------------------------------------#

EOF
